spring:
  datasource:
    url: jdbc:h2:file:/home/ubuntu/nck/data/valorant_custom
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

henrik:
  api:
    key: ${HENRIK_API_KEY}
    base-url: https://api.henrikdev.xyz